### ISSUE TITLE
能告知各模块的版本吗?

### ISSUE THREAD

**Issue by cooltnt** [sksujan58/Multivariate-time-series-forecasting-using-LSTM#1]
能告知各模块的版本吗?(包括python)  我下载后用jupyter(通过anaconda安装)运行报错
grid_search = grid_search.fit(trainX,trainY)  这里无法运行成功

**Comment by sksujan58** [comment]
@cooltnt I guess you asked me about the versions. (Sorry, don't know your language, used google translator).
{'Python': '3.9.7','numpy': '1.21.2','pandas': '1.3.4','Tensorflow': '2.7.0','keras': '2.7.0','sklearn': '1.0.1'} .This is the versions, I used.
Please , let me know if it solves your problem.

**Comment by cooltnt** [comment]
> @cooltnt I guess you asked me about the versions. (Sorry, don't know your language, used google translator). {'Python': '3.9.7','numpy': '1.21.2','pandas': '1.3.4','Tensorflow': '2.7.0','keras': '2.7.0','sklearn': '1.0.1'} .This is the versions, I used. Please , let me know if it solves your problem.

@sksujan58  I've solved it,  I think it's caused by the problem of sklearn installation
