### ISSUE TITLE
RuntimeError: Cannot clone object <keras.wrappers.scikit_learn.KerasRegressor object at 0x0000020395E76BA8>, as the constructor either does not set or modifies parameter validation_data

### ISSUE THREAD

**Issue by mapeng1995** [sksujan58/Multivariate-time-series-forecasting-using-LSTM#4]
Thanks a lot for your code, but I'm having some issues running it, don't know if you have time to help take a look

Running with jupyter notebook

**Grid_search = grid_search.fit(trainX,trainY) reports an error:**

RuntimeError: Cannot clone object <keras.wrappers.scikit_learn.KerasRegressor object at 0x0000020395E76BA8>, as the constructor either does not set or modifies parameter validation_data

Tried to fix it a few times, but still the error. I saw that someone on Ggithub said that the scikit-learn version was too high, so I uninstalled and installed 0.12.0scikit-learn, and reported an error testX, testY is undefined

I am using python3.7, tensorflow is 2.2.0, keras is 2.3.1, scikit_learn version is 1.0.2

I really can't find a solution, please help me

**Comment by sksujan58** [comment]
Hey, 
So sorry for late response. If you still did not get the solution ,this are the versions I used -
{'Python': '3.9.7','numpy': '1.21.2','pandas': '1.3.4','Tensorflow': '2.7.0','keras': '2.7.0','sklearn': '1.0.1'}.
Let me know if it helps.
