### ISSUE TITLE
DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.

### ISSUE THREAD

**Issue by CYiHang** [sksujan58/Multivariate-time-series-forecasting-using-LSTM#5]
I ran into the problem ，**DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  grid_model = KerasRegressor(build_fn=build_model,verbose=1,validation_data=(testX,testY))，** when I ran the project.How can I solve this problem

**Comment by sksujan58** [comment]
@CYiHang sorry for the late reply. This is just a deprecation warning, so just stay with the proper library versions, I guess it will not interrupt your executions.
