### ISSUE TITLE
Cannot clone object , as the constructor either does not set or modifies parameter validation_data

### ISSUE THREAD

**Issue by carbyG** [sksujan58/Multivariate-time-series-forecasting-using-LSTM#6]

**Comment by sksujan58** [comment]
@carbyG .. Please use the below versions and try to rerun the code again - 
('Python': '3.9')
'numpy': '1.21.2','pandas': '1.3.4','Tensorflow': '2.7.0','keras': '2.7.0','sklearn': '1.0.1'

**Comment by sksujan58** [comment]
Closing this issue thread for now, please reopen it if you wanna discuss more about it.
